version: '3'
  services:
    app1:
      build: ./app
      ports:
      - "5002:5000"
    app2:
      build: ./app
      ports:
      - "5003:5000"
    nginx:
      build: ./nginx
      ports:
      - "8080:6969"
      depends_on:
      - app1
      - app2